---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vs7-developer-global-viewer-role
rules:
  - apiGroups: [""]
    resources:
      - configmaps
      - deployments
      - endpoints
      - limitranges
      - namespaces
      - persistentvolumeclaims
      - persistentvolumes
      - podtemplates
      - pods
      - replicationcontrollers
      - resourcequotas
      - secrets
      - services
      - serviceaccounts
    verbs: ["list", "watch"]

  - apiGroups: [""]
    resources:
      - nodes
    verbs: ["list", "get", "watch"]

  - apiGroups: ["", "events.k8s.io"]
    resources:
      - events
    verbs: ["list", "get", "watch"]

  - apiGroups: ["apps"]
    resources:
      - replicasets
      - deployments
      - statefulsets
      - daemonsets
    verbs: ["list", "watch"]

  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["list", "watch"]

  - apiGroups: ["autoscaling"]
    resources:
      - horizontalpodautoscalers
    verbs: ["list", "watch"]

  - apiGroups: ["extensions"]
    resources:
      - ingresses
      - deployments
      - daemonsets
      - replicasets
      - services
      - configmaps
    verbs: ["list", "get", "watch"]

  - apiGroups: ["policy"]
    resources:
      - poddisruptionbudgets
    verbs: ["list", "watch"]

  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
      - ingressclasses
      - status
      - networkpolicies
    verbs: ["list", "watch"]

  - apiGroups: ["storage.k8s.io"]
    resources:
      - storageclasses
      - volumeattachments
      - csidrivers
      - csinodes
      - csistoragecapacities
    verbs: ["list", "watch"]

  - apiGroups: ["apiregistration.k8s.io"]
    resources:
      - apiservices
    verbs: ["list", "watch"]

  - apiGroups: ["coordination.k8s.io"]
    resources:
      - leases
    verbs: ["list", "watch"]

  - apiGroups: ["discovery.k8s.io"]
    resources:
      - endpointslices
    verbs: ["list", "watch"]

  - apiGroups: ["node.k8s.io"]
    resources:
      - runtimeclasses
    verbs: ["list", "watch"]

  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - clusterroles
      - clusterrolebindings
      - roles
      - rolebindings
    verbs: ["list", "watch"]

  - apiGroups: ["scheduling.k8s.io"]
    resources:
      - priorityclasses
    verbs: ["list", "watch"]

  - apiGroups: ["flowcontrol.apiserver.k8s.io"]
    resources:
      - flowschemas
      - prioritylevelconfigurations
    verbs: ["list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vs7-developer-global-viewer-rolebinding
subjects:
  - kind: User
    name: vs7-developer-role
    namespace: vs7
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name:  vs7-developer-global-viewer-role
  apiGroup: rbac.authorization.k8s.io
