---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: vs7
  name: vs7-developer-ns-admin-role
rules:
  - apiGroups: [""]
    resources:
      - configmaps
      - endpoints
      - namespaces
      - persistentvolumeclaims
      - persistentvolumes
      - podtemplates
      - pods
      - pods/log
      - pods/exec
      - pods/status
      - secrets
      - services
      - serviceaccounts
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
      - deletecollection

  - apiGroups: ["apps"]
    resources:
      - namespaces
      - deployments
      - replicasets
      - statefulsets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
      - deletecollection

  - apiGroups: ["rds.services.k8s.aws"]
    resources:
      - dbinstances
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  - apiGroups: ["s3.services.k8s.aws"]
    resources:
      - buckets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  - apiGroups: ["services.k8s.aws"]
    resources:
      - fieldexports
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: vs7
  name: vs7-developer-ns-admin-rolebinding
subjects:
  - kind: User
    name: vs7-developer-role
    namespace: vs7
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: vs7-developer-ns-admin-role
  apiGroup: rbac.authorization.k8s.io
---
