apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      name: hello-kubernetes
  template:
    metadata:
      labels:
        name: hello-kubernetes
    spec:
      containers:
        - name: app
          image: paulbouwer/hello-kubernetes:1.10.1
          env:
            - name: MESSAGE
              value: "Hello world, @mb-eks-cluster!"
            - name: RENDER_PATH_PREFIX
              value: /hello-kubernetes/
          ports:
            - containerPort: 8080

