apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes-on-path
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    name: hello-kubernetes-on-path
---
apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes-on-subdomain
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    name: hello-kubernetes-on-subdomain
