---
apiVersion: s3.services.k8s.aws/v1alpha1
kind: Bucket
metadata:
  labels:
    app.kubernetes.io/name: viewspot-studio
  name: studio-s3-bucket
  namespace: viewspot
spec:
  name: viewspot-studio-mb-eks
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: studio-s3-bucket
  namespace: viewspot
data: {}
---
apiVersion: services.k8s.aws/v1alpha1
kind: FieldExport
metadata:
  name: studio-s3-bucket
  namespace: viewspot
spec:
  to:
    name: studio-s3-bucket
    kind: configmap
  from:
    path: ".spec.name"
    resource:
      group: s3.services.k8s.aws
      kind: Bucket
      name: studio-s3-bucket
